<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Estimate;

class EstimateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {   
        //ウェブ
        
        Estimate::create([
          'category_id' => 1,         
          'item' => null,
          'content' => '演題データ作成、細部チェック、流し込み、データベース作成',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 100000,        
          'prise' => 100000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,          
          'checkitem_id' => 1,           
        ]); 
        Estimate::create([
          'category_id' => 1,         
          'item' => null,
          'content' => '演題データ作成、細部チェック、流し込み、データベース作成　※日英版',       
          'quantity' => 1.5,          
          'unit' => '式',          
          'unit_prise' => 100000,        
          'prise' => 150000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,            
          'checkitem_id' => 1,         
        ]);    
        Estimate::create([
          'category_id' => 2,         
          'item' => '日程表自動生成機能設定・設置',
          'content' => '発表形式絞込調整等を含みます。',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 30000,        
          'prise' => 30000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,           
          'checkitem_id' => 1,          
        ]);    
        Estimate::create([
          'category_id' => 2,         
          'item' => 'システム設置・設定・運用',
          'content' => '2ヶ月間',       
          'quantity' => 2,          
          'unit' => 'ヶ月',          
          'unit_prise' => 44000,        
          'prise' => 88000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);        
        Estimate::create([
          'category_id' => 2,         
          'item' => '学会ごとCSS等変更・調整設定',
          'content' => 'ヘッダ画像、バナー画像設置を含みます。',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 20000,        
          'prise' => 20000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,            
          'checkitem_id' => 1,         
        ]);        
        Estimate::create([
          'category_id' => 2,         
          'item' => '英語版対応',
          'content' => '英語版システム設置・設定',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 30000,        
          'prise' => 30000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,            
          'checkitem_id' => 1,         
        ]);        
        Estimate::create([
          'category_id' => 2,         
          'item' => null,
          'content' => '演題データ作成、細部チェック、流し込み、データベース作成',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 50000,        
          'prise' => 50000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 2,         
          'item' => 'スマホ（レスポンシブ）版対応',
          'content' => 'スマホ版設置・調整、動作確認',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 2,         
          'item' => 'スマホ（レスポンシブ）版対応',
          'content' => 'スマホ版設置・調整、動作確認　※日英版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 2,         
          'item' => null,
          'content' => '※メニューへの各種ご案内、会場マップの設置は含みません。',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);      
        
        //アプリ
        
        Estimate::create([
          'category_id' => 3,         
          'item' => '同期用システム',
          'content' => '同期用システム＆DB設置・設定、演題データ流し込み、同期チェック',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 77000,        
          'prise' => 77000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]); 
        Estimate::create([
          'category_id' => 3,         
          'item' => null,
          'content' => '※Web版運用なしの場合、デバイス同期用システム設置として本料金が発生します。',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 3,         
          'item' => null,
          'content' => '※システム運用保守・サーバー費用を含みます（2ヶ月間程度）',
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 3,         
          'item' => 'iOS版（ユニバーサル対応）',
          'content' => 'コンテナアプリ内への各学会コンテンツ生成（各種素材・コンテンツ作成含む）',       
          'quantity' => 7.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 262500,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 3,         
          'item' => 'Android版',
          'content' => 'コンテナアプリ内への各学会コンテンツ生成（各種素材・コンテンツ作成含む）',       
          'quantity' => 5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 175000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 3,         
          'item' => '英語版対応',
          'content' => '日英言語切替対応　基本機能の部分調整、表示調整、デバイス確認',       
          'quantity' => 6,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 210000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 1,        
        ]);   
        
        //オプション
        
        Estimate::create([
          'category_id' => 4,         
          'item' => 'MyAbstracts',
          'content' => 'PDF生成エンジン設置　MyAbstracts等PDF生成機能設置等（Texメタファイル作成等）',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 50000,        
          'prise' => 50000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '生成ボタン等表示設定　MyAbstracts生成ボタン、文字表示調整、ブラウザ印刷機能表示',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 20000,        
          'prise' => 20000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);       
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '各種チェック',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 120000,        
          'prise' => 120000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);       
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '表紙・本文ヘッダ設定、抄録全件出力（文字化け）チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);      
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '画像出力チェック、MyAbライブラリDB設置、生成チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);    
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '日程表PDF、演者スケジュール（人名順/日時順）表示チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => 'MyAbstracts（英語版）',
          'content' => 'PDF生成エンジン設置（※日本語版への設置が前提です）',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 80000,        
          'prise' => 80000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '生成ボタン等表示設定　MyAbstracts生成ボタン、文字表示調整、ブラウザ印刷機能表示',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);       
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '各種チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);       
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '表紙・本文ヘッダ設定、抄録全件出力（文字化け）チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);      
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '画像出力チェック、MyAbライブラリDB設置、生成チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);    
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '日程表PDF、演者スケジュール（人名順/日時順）表示チェック',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => 'アプリ版へのMyAbstracts設置',
          'content' => 'ランニング対応（連携～生成チェック）※Web版への設置が前提です。',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 17500,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 1,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => 'アプリ版へのMyAbstracts設置 ※ウェブ版運用なし',
          'content' => 'PDF生成エンジン設置　サーバ設置、PDF生成エンジン設置、サーバ利用料（2か月間）',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 50000,        
          'prise' => 50000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '各種チェック　PDF表紙・本文ヘッダ設定、抄録全件出力（文字化け）チェック',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 100000,        
          'prise' => 100000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 2,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '各種チェック（英語版）　PDF表紙・本文ヘッダ設定、抄録全件出力（文字化け）チェック',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 80000,        
          'prise' => 80000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 2,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => '管理画面設置・設定',
          'content' => '管理画面設置・設定、プッシュ通知機能、ベーシック認証設置',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 43500,        
          'prise' => 43500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 1,        
        ]);           
        Estimate::create([
          'category_id' => 4,         
          'item' => '管理画面設置・設定',
          'content' => '管理画面設置・設定、プッシュ通知機能、ベーシック認証設置　※日英版',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 43500,        
          'prise' => 65250,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 1,        
        ]);            
        Estimate::create([
          'category_id' => 4,         
          'item' => '演題データ編集システム',
          'content' => 'MICEnaviイベントアプリごとに、データ更新編集機能を設置',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 1,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => '展示（ウェブ版）',
          'content' => '出展者リストのDB作成、画像表示・ブックマーク連携チェック',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 7,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => '展示（アプリ版）',
          'content' => '企業展示情報の個別編集システム設置',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 7,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => 'ピンドロップ用マップ作成作業、マッピング作業（100社以内程度）',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 8,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '「はい/いいえ」画面設置',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 9,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => 'セッションアンケート・資料ダウンロード',
          'content' => 'セッション画面へのアンケート・資料ダウンロード機能設置',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 10,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => 'セッションアンケート・資料ダウンロード',
          'content' => 'セッション画面へのアンケート・資料ダウンロード機能設置　※日英版',       
          'quantity' => 4,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 140000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 10,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '管理画面設置（各種初期設定、初期アカウント作成、動作確認）',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 10,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会アンケート',
          'content' => '管理画面への大会アンケート機能設置',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 11,        
        ]);  
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会アンケート',
          'content' => '管理画面への大会アンケート機能設置　※日英版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 11,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会資料アップロード（インフォメーションボード）',
          'content' => '管理画面への資料アップロードの機能設置',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 12,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会資料アップロード（インフォメーションボード）',
          'content' => '管理画面への資料アップロードの機能設置　※日英版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 12,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'テキストダウンロード（セッションPDF/演題PDF）',
          'content' => '認証画面設置、PDFの設置、ボタン文言変更対応含む',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 13,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'テキストダウンロード（セッションPDF/演題PDF）',
          'content' => '認証画面設置、PDFの設置、ボタン文言変更対応含む　※日英版',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 13,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'テキストダウンロード（セッションPDF/演題PDF）',
          'content' => 'PDFの設置、ボタン文言変更対応含む',       
          'quantity' => 0.2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 7000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 14,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'テキストダウンロード（セッションPDF/演題PDF）',
          'content' => 'PDFの設置、ボタン文言変更対応含む　※日英版',       
          'quantity' => 0.4,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 14000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 14,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'デジタルポスター',
          'content' => 'ウェブ版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 15,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'デジタルポスター',
          'content' => 'ウェブ版　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 15,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'デジタルポスター',
          'content' => 'アプリ版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 15,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'デジタルポスター',
          'content' => 'アプリ版　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 15,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'ウェブ版＋アプリ版　ログイン画面の文言調整 、メニュー表示設定',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 1,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 16,        
        ]);           
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'ウェブ版＋アプリ版　ログイン画面の文言調整 、メニュー表示設定　※日英版',       
          'quantity' => 5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 175000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 1,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 16,        
        ]);           
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'ウェブ版　ログイン画面の文言調整 、メニュー表示設定',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 16,        
        ]);         
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'ウェブ版　ログイン画面の文言調整 、メニュー表示設定　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 16,        
        ]);   
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'アプリ版　ログイン画面の文言調整 、メニュー表示設定',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 16,        
        ]);       
        Estimate::create([
          'category_id' => 4,         
          'item' => 'LIVE/オンデマンド',
          'content' => 'アプリ版　ログイン画面の文言調整 、メニュー表示設定　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 16,        
        ]);    
        Estimate::create([
          'category_id' => 4,         
          'item' => '有料セミナー（中間DB連携対応）',
          'content' => 'ウェブ版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 17,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '有料セミナー（中間DB連携対応）',
          'content' => 'ウェブ版　※日英版',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 17,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '有料セミナー（中間DB連携対応）',
          'content' => 'アプリ版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 17,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '有料セミナー（中間DB連携対応）',
          'content' => 'アプリ版　※日英版',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 17,        
        ]); 
        
        Estimate::create([
          'category_id' => 4,         
          'item' => '認証付き外部リンク',
          'content' => 'ウェブ版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 18,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '認証付き外部リンク',
          'content' => 'ウェブ版　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 18,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '認証付き外部リンク',
          'content' => 'アプリ版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 18,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '認証付き外部リンク',
          'content' => 'アプリ版　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 18,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '参加証明書',
          'content' => 'ID一覧の取り込み、証明書内の表記調整',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 19,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '参加証明書',
          'content' => 'ID一覧の取り込み、証明書内の表記調整　※日英版',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 19,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '※入力フォーム項目や証明書の大幅レイアウト変更は別途御見積となります。',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 19,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '質問投稿と管理機能',
          'content' => '管理画面設置（各種初期設定、初期アカウント作成、動作確認）',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 20,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '質問投稿と管理機能',
          'content' => '管理画面設置（各種初期設定、初期アカウント作成、動作確認）　※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 20,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '各種ご案内',
          'content' => '機能設置',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 5000,        
          'prise' => 5000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 21,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'アプリ版トップ画面フッターへのバナー設置　複数画像切替表示',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 17500,        
          'prise' => 17500,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 22,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'アプリ起動時へのバナー設置　画像設置、DBへの画像・ウェブサイトリンク設置',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 23,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'アプリ起動時へのバナー設置　画像設置、DBへの画像・ウェブサイトリンク設置　※日英版',       
          'quantity' => 0.75,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 26250,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 23,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'ウェブ版左トップ　※タイルレイアウトの時のみ',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 24,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'ウェブ版バナー設置（PC左メニュー、モバイル版フッターの必要箇所に設置）',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 5000,        
          'prise' => 5000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 25,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'ウェブ版バナー設置（PC左メニュー、モバイル版フッターの必要箇所に設置）　※日英版',       
          'quantity' => 2,          
          'unit' => '式',          
          'unit_prise' => 5000,        
          'prise' => 10000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 25,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'MyAb前付・後付への広告ページ差込（PDFデータにてご提供ください）※3頁未満前提',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 26,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '広告',
          'content' => 'MyAb前付・後付への広告ページ差込（PDFデータにてご提供ください）※3頁未満前提　※日英版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 26,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会フィルタ',
          'content' => '日程表/プログラム画面上での学会フィルタ設置',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 20000,        
          'prise' => 20000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 27,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '大会フィルタ',
          'content' => '日程表/プログラム画面上での学会フィルタ設置　※日英版',       
          'quantity' => 1.5,          
          'unit' => '式',          
          'unit_prise' => 20000,        
          'prise' => 30000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 27,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '複合学会 抄録前PW制限（各学会PW設定、動作検証、入力画面文字設定）',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 28,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => null,
          'content' => '複合学会 抄録前PW制限（各学会PW設定、動作検証、入力画面文字設定）　※日英版',       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 28,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '分野フィルタ',
          'content' => '機能設置調整、画面調整',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 17500,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 29,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '分野フィルタ',
          'content' => '機能設置調整、画面調整　※日英版',       
          'quantity' => 2,          
          'unit' => '式',          
          'unit_prise' => 17500,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 29,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '関連情報フィルタ',
          'content' => '機能設置調整、画面調整',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 30,        
        ]); 
        Estimate::create([
          'category_id' => 4,         
          'item' => '関連情報フィルタ',
          'content' => '機能設置調整、画面調整　※日英版',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 30,        
        ]); 
        
        //カスタマイズ
        
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表アイコンカスタマイズ',
          'content' => '日程表アイコン　●種カスタマイズ',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 15000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 31,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表アイコンカスタマイズ',
          'content' => '日程表アイコン　●種カスタマイズ　※日英版',       
          'quantity' => 2,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 30000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 31,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'アプリ版表紙カスタマイズ',
          'content' => 'タイル張りタイプ（通常スマホ、iPhoneX、iPad縦、IPad横サイズ）',       
          'quantity' => 2.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 87500,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 32,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'アプリ版表紙カスタマイズ',
          'content' => 'タイル張りタイプ（通常スマホ、iPhoneX、iPad縦、iPad横サイズ）　※日英版',       
          'quantity' => 5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 175000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 32,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'ウェブ版トップカスタマイズ',
          'content' => 'タイル張りタイプ（PC＋モバイル）',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 33,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'ウェブ版トップカスタマイズ',
          'content' => 'タイル張りタイプ（PC＋モバイル）　※日英版',       
          'quantity' => 5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 175000,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 33,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '文言変更',
          'content' => '（★詳細記入）',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 15000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 34,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表コマ名指定（5件以上）',
          'content' => null,       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 15000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 35,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表コマ名指定（5件以上）',
          'content' => '※日英版',       
          'quantity' => 2,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 30000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 35,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表タブ(icon・文言)変更（アプリ版）',
          'content' => 'アイコン画像差し替え、文言設定',       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 15000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 36,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '日程表タブ(icon・文言)変更（アプリ版）',
          'content' => 'アイコン画像差し替え、文言設定　※日英版',       
          'quantity' => 2,          
          'unit' => '式',          
          'unit_prise' => 15000,        
          'prise' => 30000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 36,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'アプリ版トップからの参加登録サイト呼び出し',
          'content' => 'Webビューでの参加登録画面表示前提',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 37,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '会期5日間以上の日程表タブ調整（ウェブ版）',
          'content' => null,       
          'quantity' => 0.3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 10500,           
          'web_flag' => 1,        
          'app_flag' => 2,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 38,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'MyAbstracts 外字マップメンテナンス',
          'content' => '（★詳細記入）',       
          'quantity' => 1,          
          'unit' => '文字',          
          'unit_prise' => 3000,        
          'prise' => 3000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 3,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'MyAbstracts 外字作成',
          'content' => '（★詳細記入）',       
          'quantity' => 1,          
          'unit' => '文字',          
          'unit_prise' => 5000,        
          'prise' => 5000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 4,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'MyAbstracts 個別調整',
          'content' => '（★詳細記入）',       
          'quantity' => 1,          
          'unit' => '文字',          
          'unit_prise' => 3500,        
          'prise' => 3500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 5,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'MyAbstracts 全日程セッションの文言変更（見出し・ツメ）',
          'content' => null,       
          'quantity' => 0.3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 10500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 6,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'MyAbstracts 全日程セッションの文言変更（見出し・ツメ）',
          'content' => '※日英版',       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 6,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '視聴履歴メニュー設置',
          'content' => null,       
          'quantity' => 0.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 17500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 39,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '視聴履歴メニュー設置',
          'content' => '※日英版',       
          'quantity' => 1,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 39,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '共催セミナー一覧',
          'content' => 'ウェブ版＋アプリ版',       
          'quantity' => 8,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 280000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 40,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'スポンサー',
          'content' => null,       
          'quantity' => 1.5,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 52500,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 41,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'スポンサー',
          'content' => '※日英版',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 41,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'スポンサー一覧（HTML）',
          'content' => 'ウェブ版＋アプリ版　※100社程度想定　※アプリ版はWebView表示',       
          'quantity' => 3,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 105000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 3,             
          'checkitem_id' => 42,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'スポンサー一覧（HTML）',
          'content' => '※ウェブ版＋アプリ版　※100社程度想定　※アプリ版はWebView表示　※日英版',       
          'quantity' => 6,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 210000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 1,             
          'checkitem_id' => 42,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'プログラム一覧（タブ分けコマ表示）',
          'content' => 'ウェブ版＋アプリ版',       
          'quantity' => 7,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 245000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 43,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '紙面開催（日時会場無し）',
          'content' => null,       
          'quantity' => 0.8,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 28000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 44,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => '各種ご案内、開催概要作成なし',
          'content' => null,       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => -20000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 45,        
        ]);  
        Estimate::create([
          'category_id' => 5,         
          'item' => 'フロアマップ作成なし',
          'content' => null,       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => -35000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 46,        
        ]);  
        Estimate::create([
          'category_id' => 6,         
          'item' => 'Web開催IDの有効化（★記入★＊月＊日早朝＊：00対応）',
          'content' => null,       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 18000,        
          'prise' => 18000,           
          'web_flag' => 0,        
          'app_flag' => 0,          
          'machine_both' => 2,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 47,        
        ]);  
        Estimate::create([
          'category_id' => 7,         
          'item' => '★記入★＊月＊日',
          'content' => '★★入★演題情報更新（＊件）　※アプリ版含む',       
          'quantity' => 1,          
          'unit' => '回',          
          'unit_prise' => 15000,        
          'prise' => 15000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 48,        
        ]);  
        Estimate::create([
          'category_id' => 7,         
          'item' => '★記入★＊月＊日',
          'content' => '★★入★演題情報更新（＊件）　※ウェブ版のみ',       
          'quantity' => 1,          
          'unit' => '回',          
          'unit_prise' => 3000,        
          'prise' => 3000,           
          'web_flag' => 1,        
          'app_flag' => 0,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 48,        
        ]);  
        Estimate::create([
          'category_id' => 8,         
          'item' => 'アプリ側作業（2人日×2デバイス）',
          'content' => '前回大会以降にMICEnaviへ追加した新機能の横展開',       
          'quantity' => 4,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 140000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 49,        
        ]);  
        Estimate::create([
          'category_id' => 8,         
          'item' => null,
          'content' => '新OS新デバイス対応の横展開',       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 49,        
        ]);  
        Estimate::create([
          'category_id' => 8,         
          'item' => 'コンテナ側管理画面の作業',
          'content' => '前回大会以降にコンテナ側管理画面へ追加した新機能の横展開',       
          'quantity' => 2,          
          'unit' => '人日',          
          'unit_prise' => 35000,        
          'prise' => 70000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 49,        
        ]);  
        Estimate::create([
          'category_id' => 8,         
          'item' => 'バージョンアップ',
          'content' => null,       
          'quantity' => 1,          
          'unit' => '式',          
          'unit_prise' => 25000,        
          'prise' => 25000,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 49,        
        ]);  
        Estimate::create([
          'category_id' => 9,         
          'item' => '※アプリランチョン連携対応は、ランチョンセミナー整理券発券機の御見積に含まれます。',
          'content' => null,       
          'quantity' => null,          
          'unit' => null,          
          'unit_prise' => null,        
          'prise' => null,           
          'web_flag' => 2,        
          'app_flag' => 1,          
          'machine_both' => 0,           
          'ja_flag' => 0,           
          'eng_flag' => 0,           
          'lang_both' => 2,             
          'checkitem_id' => 50,        
        ]);  
/*        
        Estimate::create([
          'category_id' => ,         
          'item' => '',
          'content' => '',       
          'quantity' => ,          
          'unit' => '',          
          'unit_prise' => ,        
          'prise' => ,           
          'web_flag' => ,        
          'app_flag' => ,          
          'machine_both' => ,           
          'ja_flag' => ,           
          'eng_flag' => ,           
          'lang_both' => ,             
          'checkitem_id' => ,        
        ]);   
*/        
    }
}
